### PR TITLE
Workflow for linux 

### PR DESCRIPTION
**Pull request by purmortal**
Create Action workflow for linux.

### CODE REVIEW

**Comment by conradtchan** [comment]
I noticed there are some leftover commented out commands from debugging. I've tidied them up 🙂

**Comment by purmortal** [comment]
All good, thanks for that!

Warm regards,
Purmortal
(Zixian Wang)

Purmortal / Zixian Wang (王梓先)  | PhD student (thesis submitted)
The University of Sydney
Faculty of Science, School of Physics, Sydney Institute for Astronomy (SIfA)
Rm 335A | +61 0410778968 | School of Physics A28
The University of Sydney | NSW | 2006 | AUSTRALIA
***@***.*** ***@***.***>  |  ***@***.******@***.***>

From: Conrad Chan ***@***.***>
Date: Friday, 1 September 2023 at 1:54 pm
To: cpinte/mcfost ***@***.***>
Cc: 王梓先 ***@***.***>, Author ***@***.***>
Subject: Re: [cpinte/mcfost] Workflow for linux (PR #66)

I noticed there are some leftover commented out commands from debugging. I've tidied them up 🙂

**Comment by conradtchan** [comment]
Hi @cpinte, this PR to add a build test for linux is ready. Could you please have a look and merge it if you're happy with it?

**Comment by cpinte** [comment]
This looks great. Thanks !!

**Review by cpinte — APPROVED** [review]

**Pull request merged**
