### PR TITLE
Release workflow

### PR DESCRIPTION
**Pull request by dliptai**
Create a workflow to automatically upload binaries to a release when published

### CODE REVIEW

**Comment by dliptai** [comment]
MacOS binary seems to work ok...

The linux binary is being dynamically linked to the HDF5 library at the moment because we're using the system HDF5 instead of manually building only the static HDF5 library

**Comment by dliptai** [comment]
MacOS binary dynamically links to cfitsio and hdf5
```
$ otool -L mcfost_macos-12 
mcfost_macos-12:
	/usr/local/opt/cfitsio/lib/libcfitsio.10.dylib (compatibility version 10.0.0, current version 10.4.3)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/local/opt/hdf5/lib/libhdf5_fortran.310.dylib (compatibility version 312.0.0, current version 312.1.0)
	/usr/local/opt/hdf5/lib/libhdf5.310.dylib (compatibility version 313.0.0, current version 313.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/local/opt/gcc/lib/gcc/current/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```

**Comment by dliptai** [comment]
big changes are:
- build with static=yes
- build local hdf5 on MacOS too, to make sure we use the static lib (we now just use `install.sh` on both systems)
- add flags to make sure libgfortran and libquadmath are statically linked

**Review by conradtchan — APPROVED** [review]

**Comment by dliptai** [comment]
@cpinte This is ready to be merged

**Review by conradtchan — APPROVED** [review]

**Review by cpinte — APPROVED** [review]

**Comment by cpinte** [comment]
Thanks !

**Pull request merged**
